<<<<<<< HEAD
=======
blogger_menu:
    resource: "@BloggerMenuBundle/Resources/config/routing.yml"
    prefix:   /

>>>>>>> 187c66b7709525b773b1b0c18b9db5e6507c8389
blogger_gen:
    resource: "@BloggerGenBundle/Resources/config/routing.yml"
    prefix:   /

